disabled_rules:
  - identifier_name
  - trailing_whitespace

excluded:
  - Carthage
  - Pods
  - Saitynas_App_2Tests
  - Saitynas_App_2UITests

file_length:
  warning: 300
  error: 500

custom_rules:
  mark_formatting:
    included: ".*\\.swift"
    name: "MARK formatting"
    regex: '(// MARK: [^-])'
    capture_group: 0
    match_kinds:
      - comment
    message: "Invalid Mark comment formatting"
    severity: error
